"""
Django settings for todo_list_app project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0&^245(f-bh)ryu501kkj$b@za6m%$$e%a^amlwbxhx9dtshf1'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG=True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base.apps.BaseConfig','csp'
]

MIDDLEWARE = [
    'base.middleware.CSPMiddleware',
    # 'base.middleware.XContentOptionsMiddleware',
    'base.middleware.RemoveServerHeaderMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'todo_list_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{'staticfiles':'django.templatetags.static',}
        },
    },
]

WSGI_APPLICATION = 'todo_list_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_URL = 'login'
# Set SESSION_COOKIE_SECURE to True if using HTTPS
SESSION_COOKIE_SECURE = True

# Set SESSION_COOKIE_HTTPONLY to True
SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_HTTPONLY = True
SERVER_HEADER = 'MyAwesomeApp'
SECURE_CONTENT_TYPE_NOSNIFF = True
CSRF_COOKIE_SECURE = True
CSRF_USE_SESSIONS = True

CSP_INCLUDE_NONCE_IN = ['style-src']

CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "http://127.0.0.1:8000", "https://127.0.0.1:8000")
CSP_IMG_SRC = ("'self'","http://127.0.0.1:8000",  "https://127.0.0.1:8000")
CSP_FAVICON_SRC = ("'self'", "http://127.0.0.1:8000",  "https://127.0.0.1:8000")
CSP_STYLE_SRC = ("'self'", 'http://127.0.0.1:8000',  "https://127.0.0.1:8000")
CSP_CONNECT_SRC = ("'self'", "http://127.0.0.1:8000",  "https://127.0.0.1:8000")
CSP_FRAME_SRC = ("'self'", "http://127.0.0.1:8000",  "https://127.0.0.1:8000")
CSP_FRAME_ANCESTORS = ("'self'", "http://127.0.0.1:8000",  "https://127.0.0.1:8000")
CSP_FONT_SRC = ("'self'", "http://127.0.0.1:8000",  "https://127.0.0.1:8000")
CSP_MEDIA_SRC = ("'self'", "http://127.0.0.1:8000",  "https://127.0.0.1:8000")
CSP_OBJECT_SRC = ("'self'", "http://127.0.0.1:8000",  "https://127.0.0.1:8000")
CSP_MANIFEST_SRC = ("'self'", "http://127.0.0.1:8000",  "https://127.0.0.1:8000")
CSP_FORM_ACTION = ("'self'", "http://127.0.0.1:8000",  "https://127.0.0.1:8000")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# Allow these specific resources


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "projectapp/static"),
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
